<?php $this->headtitle("Blog");?>
<h1>Blog</h1>

<a href="<?=$this->url('post', ['action'=>'add'])?>"
	class="btn btn-primary">New Post</a>
<br />
<br />
<table class="table">
	<tr>
		<th>Title</th>
		<th>Action</th>
	</tr>
<?php foreach ($posts as $post): ?>
	<tr>
		<td><?=$this->escapehtml($post->title);?></td>
		<td>
			<a href="<?=$this->url('post', ['action'=>'edit','id'=>$post->id])?>"class="btn btn-sm btn-info">Edit</a> 
			<a href="<?=$this->url('post', ['action'=>'delete', 'id'=>$post->id])?>"class="btn btn-sm btn-danger">Delete</a>
		</td>

	</tr>
<?php endforeach; ?>
</table>